### ISSUE TITLE
Update examples in projects

### ISSUE THREAD

**Issue by BlueGlassBlock** [GraiaProject/Document#1]
Since Python 3.10, using [asyncio.get_event_loop()](https://docs.python.org/zh-cn/3.10/library/asyncio-eventloop.html#asyncio.get_event_loop) to create event loops is deprecated.

Please update documentations by replacing [asyncio.get_event_loop()](https://docs.python.org/zh-cn/3.10/library/asyncio-eventloop.html#asyncio.get_event_loop) with [asyncio.create_event_loop()](https://docs.python.org/zh-cn/3.10/library/asyncio-eventloop.html#asyncio.new_event_loop)

Affected repositories / pages:
[BroadcastControl](github.com/GraiaProject/BroadcastControl)
[Application](github.com/GraiaProject/Application)
[Scheduler](https://github.com/GraiaProject/Scheduler)
[Document](https://github.com/GreyElaina/GraiaDocument)

**Comment by GreyElaina** [comment]
fuck psf.
